export type Verb = {
  infinitive: string;
  english: string;
  conjugations: string[];
  examples: string[];
};

export type VerbSet = {
  name: string;
  verbs: Verb[];
  explanation: {
    whenToUse: string;
    importantRules: string[];
    regularPattern: string;
  };
};

export type VerbSets = {
  [key: string]: VerbSet;
};

export const verbSets: VerbSets = {
  presentSubjunctive: {
    name: "Present Subjunctive",
    explanation: {
      whenToUse:
        "Use the present subjunctive to express doubt, wishes, emotions, recommendations, or actions that may or may not happen. Common triggers include: que, ojalá, es importante que, espero que.",
      importantRules: [
        "Formed from the yo form of present indicative, drop -o, add opposite endings",
        "AR verbs: -e, -es, -e, -emos, -éis, -en",
        "ER/IR verbs: -a, -as, -a, -amos, -áis, -an",
        "Many common verbs are irregular",
      ],
      regularPattern:
        "hablar → hable, hables, hable, hablemos, habléis, hablen",
    },
    verbs: [
      {
        infinitive: "ser",
        english: "to be",
        conjugations: ["sea", "seas", "sea", "seamos", "seáis", "sean"],
        examples: [
          "Espero que yo sea feliz.",
          "Quiero que tú seas honesto.",
          "Es importante que él sea puntual.",
          "Ojalá que nosotros seamos amigos.",
          "Espero que vosotros seáis buenos estudiantes.",
          "Es necesario que ellos sean responsables.",
        ],
      },
      {
        infinitive: "ir",
        english: "to go",
        conjugations: ["vaya", "vayas", "vaya", "vayamos", "vayáis", "vayan"],
        examples: [
          "Dudo que yo vaya a la fiesta.",
          "No creo que tú vayas al cine.",
          "Espero que ella vaya al médico.",
          "Sugiero que nosotros vayamos juntos.",
          "Es posible que vosotros vayáis mañana.",
          "Quiero que ellos vayan a la escuela.",
        ],
      },
      {
        infinitive: "haber",
        english: "to have (auxiliary)",
        conjugations: ["haya", "hayas", "haya", "hayamos", "hayáis", "hayan"],
        examples: [
          "Es posible que yo haya terminado el trabajo.",
          "Dudo que tú hayas estudiado suficiente.",
          "No creo que ella haya llegado todavía.",
          "Espero que nosotros hayamos aprobado el examen.",
          "Es probable que vosotros hayáis visto la película.",
          "Me alegro de que ellos hayan venido a la reunión.",
        ],
      },
      {
        infinitive: "saber",
        english: "to know",
        conjugations: ["sepa", "sepas", "sepa", "sepamos", "sepáis", "sepan"],
        examples: [
          "No creo que yo sepa la respuesta correcta.",
          "Dudo que tú sepas hablar francés.",
          "Es importante que él sepa la verdad.",
          "Ojalá que nosotros sepamos qué hacer.",
          "No pienso que vosotros sepáis cocinar paella.",
          "Espero que ellos sepan dónde está el hospital.",
        ],
      },
      {
        infinitive: "estar",
        english: "to be",
        conjugations: ["esté", "estés", "esté", "estemos", "estéis", "estén"],
        examples: [
          "Espero que yo esté listo para el examen.",
          "Quiero que tú estés tranquilo durante la prueba.",
          "Es necesario que ella esté en casa antes de las diez.",
          "Ojalá que nosotros estemos de vacaciones pronto.",
          "Dudo que vosotros estéis cansados todavía.",
          "No creo que ellos estén en la oficina.",
        ],
      },
      {
        infinitive: "dar",
        english: "to give",
        conjugations: ["dé", "des", "dé", "demos", "deis", "den"],
        examples: [
          "Espero que yo dé una buena impresión.",
          "Quiero que tú des tu opinión sincera.",
          "Es importante que él dé el dinero al profesor.",
          "Sugiero que nosotros demos un paseo por el parque.",
          "No creo que vosotros deis suficiente tiempo al proyecto.",
          "Espero que ellos den una respuesta clara.",
        ],
      },
      {
        infinitive: "ver",
        english: "to see",
        conjugations: ["vea", "veas", "vea", "veamos", "veáis", "vean"],
        examples: [
          "No creo que yo vea la diferencia entre ellos.",
          "Dudo que tú veas la televisión esta noche.",
          "Espero que ella vea al doctor mañana.",
          "Sugiero que nosotros veamos esa película juntos.",
          "Es posible que vosotros veáis a María en la fiesta.",
          "Quiero que ellos vean los resultados del trabajo.",
        ],
      },
      {
        infinitive: "tener",
        english: "to have",
        conjugations: [
          "tenga",
          "tengas",
          "tenga",
          "tengamos",
          "tengáis",
          "tengan",
        ],
        examples: [
          "Espero que yo tenga tiempo para estudiar.",
          "Quiero que tú tengas éxito en tu nuevo trabajo.",
          "Es importante que él tenga paciencia con los niños.",
          "Ojalá que nosotros tengamos buen tiempo para el viaje.",
          "Dudo que vosotros tengáis suficiente dinero.",
          "No creo que ellos tengan la información necesaria.",
        ],
      },
      {
        infinitive: "venir",
        english: "to come",
        conjugations: [
          "venga",
          "vengas",
          "venga",
          "vengamos",
          "vengáis",
          "vengan",
        ],
        examples: [
          "Dudo que yo venga a la reunión tarde.",
          "Espero que tú vengas a mi fiesta de cumpleaños.",
          "Quiero que ella venga con nosotros al cine.",
          "Sugiero que nosotros vengamos temprano mañana.",
          "Es probable que vosotros vengáis en coche.",
          "No creo que ellos vengan este fin de semana.",
        ],
      },
      {
        infinitive: "hacer",
        english: "to do/make",
        conjugations: ["haga", "hagas", "haga", "hagamos", "hagáis", "hagan"],
        examples: [
          "Es necesario que yo haga mi tarea esta noche.",
          "Quiero que tú hagas el favor de ayudarme.",
          "Espero que él haga un buen trabajo en el proyecto.",
          "Sugiero que nosotros hagamos una pausa ahora.",
          "Dudo que vosotros hagáis todo el trabajo hoy.",
          "Es importante que ellos hagan ejercicio regularmente.",
        ],
      },
      {
        infinitive: "poner",
        english: "to put",
        conjugations: [
          "ponga",
          "pongas",
          "ponga",
          "pongamos",
          "pongáis",
          "pongan",
        ],
        examples: [
          "Quiero que yo ponga más atención en clase.",
          "Es necesario que tú pongas la mesa para la cena.",
          "Espero que ella ponga las llaves en el cajón.",
          "Sugiero que nosotros pongamos la música más baja.",
          "Dudo que vosotros pongáis los libros en orden.",
          "Es importante que ellos pongan los documentos aquí.",
        ],
      },
      {
        infinitive: "decir",
        english: "to say/tell",
        conjugations: ["diga", "digas", "diga", "digamos", "digáis", "digan"],
        examples: [
          "No creo que yo diga la verdad completa.",
          "Quiero que tú digas lo que piensas realmente.",
          "Es importante que él diga su nombre al entrar.",
          "Espero que nosotros digamos las cosas correctas.",
          "Dudo que vosotros digáis la verdad a vuestros padres.",
          "No pienso que ellos digan nada importante.",
        ],
      },
      {
        infinitive: "traer",
        english: "to bring",
        conjugations: [
          "traiga",
          "traigas",
          "traiga",
          "traigamos",
          "traigáis",
          "traigan",
        ],
        examples: [
          "Espero que yo traiga suficiente comida para todos.",
          "Quiero que tú traigas tu guitarra a la fiesta.",
          "Es necesario que ella traiga los documentos mañana.",
          "Sugiero que nosotros traigamos vino a la cena.",
          "Dudo que vosotros traigáis todo lo necesario.",
          "Espero que ellos traigan buenas noticias.",
        ],
      },
      {
        infinitive: "salir",
        english: "to leave/go out",
        conjugations: [
          "salga",
          "salgas",
          "salga",
          "salgamos",
          "salgáis",
          "salgan",
        ],
        examples: [
          "No creo que yo salga esta noche porque estoy cansado.",
          "Dudo que tú salgas con ese tiempo tan malo.",
          "Espero que ella salga del hospital pronto.",
          "Sugiero que nosotros salgamos a caminar después de comer.",
          "Es posible que vosotros salgáis temprano del trabajo.",
          "Quiero que ellos salgan por la puerta principal.",
        ],
      },
      {
        infinitive: "conocer",
        english: "to know (person/place)",
        conjugations: [
          "conozca",
          "conozcas",
          "conozca",
          "conozcamos",
          "conozcáis",
          "conozcan",
        ],
        examples: [
          "Espero que yo conozca a gente interesante en la universidad.",
          "Quiero que tú conozcas a mi familia este fin de semana.",
          "Es importante que él conozca las reglas del juego.",
          "Ojalá que nosotros conozcamos Madrid el próximo año.",
          "Dudo que vosotros conozcáis a todos los invitados.",
          "Espero que ellos conozcan el camino al museo.",
        ],
      },
      {
        infinitive: "caber",
        english: "to fit",
        conjugations: [
          "quepa",
          "quepas",
          "quepa",
          "quepamos",
          "quepáis",
          "quepan",
        ],
        examples: [
          "Dudo que yo quepa en ese vestido pequeño.",
          "No creo que tú quepas en el coche con nosotros.",
          "Es posible que ella quepa en el ascensor con todos.",
          "No pienso que nosotros quepamos en esa habitación pequeña.",
          "Dudo que vosotros quepáis en la foto todos juntos.",
          "No creo que ellos quepan en la mesa para seis personas.",
        ],
      },
    ],
  },
  imperfectSubjunctive: {
    name: "Imperfect Subjunctive",
    explanation: {
      whenToUse:
        "Use the imperfect subjunctive in the same contexts as present subjunctive, but when the main clause is in the past. Also used for contrary-to-fact conditions (si clauses).",
      importantRules: [
        "Based on the ellos form of preterite: remove -ron, add endings",
        "Two forms exist: -ra/-ras/-ra/-ramos/-rais/-ran (more common)",
        "Or: -se/-ses/-se/-semos/-seis/-sen (more formal)",
        "If preterite is irregular, imperfect subjunctive is irregular",
      ],
      regularPattern:
        "hablar → hablara/hablase, hablaras/hablases, hablara/hablase...",
    },
    verbs: [
      {
        infinitive: "ser",
        english: "to be",
        conjugations: [
          "fuera",
          "fueras",
          "fuera",
          "fuéramos",
          "fuerais",
          "fueran",
        ],
        examples: [
          "Mi madre quería que yo fuera médico.",
          "Te pedí que tú fueras más amable con él.",
          "Si ella fuera más alta, podría jugar al baloncesto.",
          "El profesor sugirió que nosotros fuéramos al museo.",
          "Dudaba que vosotros fuerais capaces de hacerlo.",
          "Si ellos fueran ricos, viajarían por el mundo.",
        ],
      },
      {
        infinitive: "ir",
        english: "to go",
        conjugations: [
          "fuera",
          "fueras",
          "fuera",
          "fuéramos",
          "fuerais",
          "fueran",
        ],
        examples: [
          "Mi padre quería que yo fuera a la universidad.",
          "Te pedí que tú fueras al supermercado conmigo.",
          "Si ella fuera al médico, se sentiría mejor.",
          "Nos pidieron que nosotros fuéramos a la reunión.",
          "Esperaba que vosotros fuerais a visitarla.",
          "Si ellos fueran al parque, verían a sus amigos.",
        ],
      },
      {
        infinitive: "estar",
        english: "to be",
        conjugations: [
          "estuviera",
          "estuvieras",
          "estuviera",
          "estuviéramos",
          "estuvierais",
          "estuvieran",
        ],
        examples: [
          "Esperaba que yo estuviera preparado para el examen.",
          "Quería que tú estuvieras listo a las ocho.",
          "Si él estuviera aquí, nos ayudaría con el problema.",
          "Nos pidieron que nosotros estuviéramos en silencio.",
          "Dudaba que vosotros estuvierais contentos con la decisión.",
          "Si ellos estuvieran enfermos, no vendrían a trabajar.",
        ],
      },
      {
        infinitive: "tener",
        english: "to have",
        conjugations: [
          "tuviera",
          "tuvieras",
          "tuviera",
          "tuviéramos",
          "tuvierais",
          "tuvieran",
        ],
        examples: [
          "Ojalá que yo tuviera más tiempo para leer.",
          "Si tú tuvieras dinero, comprarías un coche nuevo.",
          "Me pidió que ella tuviera una segunda oportunidad.",
          "Si nosotros tuviéramos una casa grande, haríamos una fiesta.",
          "Esperaba que vosotros tuvierais cuidado en el viaje.",
          "Si ellos tuvieran paciencia, terminarían el proyecto.",
        ],
      },
      {
        infinitive: "hacer",
        english: "to do/make",
        conjugations: [
          "hiciera",
          "hicieras",
          "hiciera",
          "hiciéramos",
          "hicierais",
          "hicieran",
        ],
        examples: [
          "Me pidió que yo hiciera la comida para la cena.",
          "Si tú hicieras ejercicio, te sentirías mejor.",
          "Quería que él hiciera su tarea antes de jugar.",
          "Nos sugirieron que nosotros hiciéramos una reserva.",
          "Esperaba que vosotros hicierais el trabajo a tiempo.",
          "Si ellos hicieran más esfuerzo, aprobarían el examen.",
        ],
      },
      {
        infinitive: "poder",
        english: "to be able/can",
        conjugations: [
          "pudiera",
          "pudieras",
          "pudiera",
          "pudiéramos",
          "pudierais",
          "pudieran",
        ],
        examples: [
          "Ojalá que yo pudiera ir contigo al concierto.",
          "Si tú pudieras venir, sería fantástico.",
          "Esperaba que ella pudiera resolver el problema.",
          "Si nosotros pudiéramos volar, viajaríamos más seguido.",
          "Quería que vosotros pudierais participar en el evento.",
          "Si ellos pudieran hablar español, entenderían mejor.",
        ],
      },
      {
        infinitive: "poner",
        english: "to put",
        conjugations: [
          "pusiera",
          "pusieras",
          "pusiera",
          "pusiéramos",
          "pusierais",
          "pusieran",
        ],
        examples: [
          "Me pidió que yo pusiera la mesa para seis personas.",
          "Si tú pusieras más atención, entenderías la lección.",
          "Quería que él pusiera los libros en la estantería.",
          "Nos sugirieron que nosotros pusiéramos flores en la mesa.",
          "Esperaba que vosotros pusierais orden en la habitación.",
          "Si ellos pusieran más empeño, tendrían mejores resultados.",
        ],
      },
      {
        infinitive: "saber",
        english: "to know",
        conjugations: [
          "supiera",
          "supieras",
          "supiera",
          "supiéramos",
          "supierais",
          "supieran",
        ],
        examples: [
          "Ojalá que yo supiera la respuesta a tu pregunta.",
          "Si tú supieras cocinar, prepararías comidas deliciosas.",
          "No creía que ella supiera hablar tres idiomas.",
          "Si nosotros supiéramos la verdad, actuaríamos diferente.",
          "Dudaba que vosotros supierais dónde estaba la llave.",
          "Si ellos supieran conducir, podrían ir en coche.",
        ],
      },
      {
        infinitive: "venir",
        english: "to come",
        conjugations: [
          "viniera",
          "vinieras",
          "viniera",
          "viniéramos",
          "vinierais",
          "vinieran",
        ],
        examples: [
          "Me pidió que yo viniera temprano a la oficina.",
          "Si tú vinieras a la fiesta, te divertirías mucho.",
          "Esperaba que ella viniera a mi graduación.",
          "Nos sugirieron que nosotros viniéramos con nuestras familias.",
          "Quería que vosotros vinierais a visitarnos este verano.",
          "Si ellos vinieran en tren, llegarían más rápido.",
        ],
      },
      {
        infinitive: "decir",
        english: "to say/tell",
        conjugations: [
          "dijera",
          "dijeras",
          "dijera",
          "dijéramos",
          "dijerais",
          "dijeran",
        ],
        examples: [
          "Me pidió que yo dijera la verdad sobre lo ocurrido.",
          "Si tú dijeras lo que piensas, todos te entenderían mejor.",
          "Quería que él dijera su opinión en la reunión.",
          "Nos pidieron que nosotros dijéramos nuestros nombres.",
          "Esperaba que vosotros dijerais algo en su defensa.",
          "Si ellos dijeran la verdad, no habría problemas.",
        ],
      },
      {
        infinitive: "traer",
        english: "to bring",
        conjugations: [
          "trajera",
          "trajeras",
          "trajera",
          "trajéramos",
          "trajerais",
          "trajeran",
        ],
        examples: [
          "Me pidió que yo trajera vino para la cena.",
          "Si tú trajeras tu cámara, podríamos tomar fotos.",
          "Quería que ella trajera a su hermano a la fiesta.",
          "Nos sugirieron que nosotros trajéramos regalos para todos.",
          "Esperaba que vosotros trajerais la comida a tiempo.",
          "Si ellos trajeran sus instrumentos, podríamos tocar música.",
        ],
      },
      {
        infinitive: "dar",
        english: "to give",
        conjugations: [
          "diera",
          "dieras",
          "diera",
          "diéramos",
          "dierais",
          "dieran",
        ],
        examples: [
          "Esperaba que yo diera una buena presentación.",
          "Si tú dieras más tiempo al proyecto, sería perfecto.",
          "Quería que él diera su opinión sobre el asunto.",
          "Nos pidieron que nosotros diéramos una donación.",
          "Esperaba que vosotros dierais una respuesta clara.",
          "Si ellos dieran permiso, podríamos empezar ahora.",
        ],
      },
      {
        infinitive: "haber",
        english: "to have (auxiliary)",
        conjugations: [
          "hubiera",
          "hubieras",
          "hubiera",
          "hubiéramos",
          "hubierais",
          "hubieran",
        ],
        examples: [
          "Si yo hubiera sabido, no habría venido.",
          "Ojalá que tú hubieras estudiado más para el examen.",
          "Si ella hubiera llegado temprano, nos habría visto.",
          "Si nosotros hubiéramos tenido dinero, habríamos comprado la casa.",
          "Si vosotros hubierais avisado, habríamos preparado comida.",
          "Si ellos hubieran venido, habríamos ido al cine juntos.",
        ],
      },
      {
        infinitive: "querer",
        english: "to want",
        conjugations: [
          "quisiera",
          "quisieras",
          "quisiera",
          "quisiéramos",
          "quisierais",
          "quisieran",
        ],
        examples: [
          "Quisiera que yo pudiera ayudarte más.",
          "Si tú quisieras, podríamos ir al teatro esta noche.",
          "No creía que ella quisiera venir con nosotros.",
          "Si nosotros quisiéramos, podríamos terminar hoy mismo.",
          "Pensaba que vosotros quisierais participar en el juego.",
          "Si ellos quisieran aprender, tendrían que practicar más.",
        ],
      },
      {
        infinitive: "conducir",
        english: "to drive",
        conjugations: [
          "condujera",
          "condujeras",
          "condujera",
          "condujéramos",
          "condujerais",
          "condujeran",
        ],
        examples: [
          "Me pidió que yo condujera con más cuidado.",
          "Si tú condujeras más despacio, sería más seguro.",
          "Esperaba que él condujera el camión al almacén.",
          "Nos sugirieron que nosotros condujéramos por la autopista.",
          "Quería que vosotros condujerais turnándose en el viaje.",
          "Si ellos condujeran toda la noche, llegarían mañana temprano.",
        ],
      },
    ],
  },
  preterite: {
    name: "Preterite",
    explanation: {
      whenToUse:
        "Use the preterite for completed actions in the past with a definite beginning and end. Expresses actions that happened once, a specific number of times, or during a defined period.",
      importantRules: [
        "AR verbs: -é, -aste, -ó, -amos, -asteis, -aron",
        "ER/IR verbs: -í, -iste, -ió, -imos, -isteis, -ieron",
        "Many common verbs have irregular stems",
        "Ser and ir share the same preterite forms",
      ],
      regularPattern:
        "hablar → hablé, hablaste, habló, hablamos, hablasteis, hablaron",
    },
    verbs: [
      {
        infinitive: "ser",
        english: "to be",
        conjugations: ["fui", "fuiste", "fue", "fuimos", "fuisteis", "fueron"],
        examples: [
          "Yo fui el mejor estudiante de la clase.",
          "Tú fuiste muy amable con mi familia.",
          "Ella fue mi profesora el año pasado.",
          "Nosotros fuimos compañeros de trabajo por cinco años.",
          "Vosotros fuisteis los ganadores del concurso.",
          "Ellos fueron mis vecinos cuando vivía en Madrid.",
        ],
      },
      {
        infinitive: "ir",
        english: "to go",
        conjugations: ["fui", "fuiste", "fue", "fuimos", "fuisteis", "fueron"],
        examples: [
          "Yo fui al mercado esta mañana.",
          "Tú fuiste a Barcelona el mes pasado.",
          "Él fue al médico ayer por la tarde.",
          "Nosotros fuimos a la playa el verano pasado.",
          "Vosotros fuisteis al concierto sin mí.",
          "Ellos fueron de vacaciones a Italia en julio.",
        ],
      },
      {
        infinitive: "hacer",
        english: "to do/make",
        conjugations: [
          "hice",
          "hiciste",
          "hizo",
          "hicimos",
          "hicisteis",
          "hicieron",
        ],
        examples: [
          "Yo hice mi tarea anoche antes de dormir.",
          "Tú hiciste un pastel delicioso para la fiesta.",
          "Ella hizo todos los ejercicios del libro.",
          "Nosotros hicimos una reserva en el restaurante.",
          "Vosotros hicisteis un gran esfuerzo en el proyecto.",
          "Ellos hicieron una donación a la organización benéfica.",
        ],
      },
      {
        infinitive: "tener",
        english: "to have",
        conjugations: [
          "tuve",
          "tuviste",
          "tuvo",
          "tuvimos",
          "tuvisteis",
          "tuvieron",
        ],
        examples: [
          "Yo tuve una reunión importante ayer.",
          "Tú tuviste suerte en el examen final.",
          "Él tuvo un accidente de coche el mes pasado.",
          "Nosotros tuvimos invitados en casa todo el fin de semana.",
          "Vosotros tuvisteis un problema con el ordenador.",
          "Ellos tuvieron una fiesta sorpresa para su madre.",
        ],
      },
      {
        infinitive: "estar",
        english: "to be",
        conjugations: [
          "estuve",
          "estuviste",
          "estuvo",
          "estuvimos",
          "estuvisteis",
          "estuvieron",
        ],
        examples: [
          "Yo estuve en París durante tres semanas.",
          "Tú estuviste enfermo la semana pasada.",
          "Ella estuvo muy ocupada todo el día.",
          "Nosotros estuvimos en la biblioteca hasta tarde.",
          "Vosotros estuvisteis en la reunión esta mañana.",
          "Ellos estuvieron de vacaciones en las montañas.",
        ],
      },
      {
        infinitive: "poder",
        english: "to be able/can",
        conjugations: [
          "pude",
          "pudiste",
          "pudo",
          "pudimos",
          "pudisteis",
          "pudieron",
        ],
        examples: [
          "Yo pude terminar el trabajo a tiempo.",
          "Tú pudiste resolver el problema difícil.",
          "Él pudo llegar temprano a la cita.",
          "Nosotros pudimos ver la película completa.",
          "Vosotros pudisteis encontrar las llaves perdidas.",
          "Ellos pudieron comprar los billetes para el concierto.",
        ],
      },
      {
        infinitive: "poner",
        english: "to put",
        conjugations: [
          "puse",
          "pusiste",
          "puso",
          "pusimos",
          "pusisteis",
          "pusieron",
        ],
        examples: [
          "Yo puse las llaves en la mesa de la entrada.",
          "Tú pusiste mucho esfuerzo en el proyecto final.",
          "Ella puso la ropa en el armario después de lavarla.",
          "Nosotros pusimos las flores en el jarrón nuevo.",
          "Vosotros pusisteis la música muy alta anoche.",
          "Ellos pusieron los libros en orden alfabético.",
        ],
      },
      {
        infinitive: "saber",
        english: "to know",
        conjugations: [
          "supe",
          "supiste",
          "supo",
          "supimos",
          "supisteis",
          "supieron",
        ],
        examples: [
          "Yo supe la noticia ayer por la tarde.",
          "Tú supiste la verdad antes que nadie.",
          "Él supo que aprobó el examen esta mañana.",
          "Nosotros supimos del accidente por las noticias.",
          "Vosotros supisteis la respuesta correcta inmediatamente.",
          "Ellos supieron que ganaron el premio ayer.",
        ],
      },
      {
        infinitive: "venir",
        english: "to come",
        conjugations: [
          "vine",
          "viniste",
          "vino",
          "vinimos",
          "vinisteis",
          "vinieron",
        ],
        examples: [
          "Yo vine a tu casa temprano esta mañana.",
          "Tú viniste caminando desde la estación.",
          "Ella vino sola a la fiesta anoche.",
          "Nosotros vinimos en autobús desde el centro.",
          "Vosotros vinisteis sin avisar el domingo pasado.",
          "Ellos vinieron con regalos para todos los niños.",
        ],
      },
      {
        infinitive: "decir",
        english: "to say/tell",
        conjugations: [
          "dije",
          "dijiste",
          "dijo",
          "dijimos",
          "dijisteis",
          "dijeron",
        ],
        examples: [
          "Yo dije la verdad sobre lo que pasó.",
          "Tú dijiste que vendrías a las ocho.",
          "Él dijo que no podía venir a la reunión.",
          "Nosotros dijimos adiós a nuestros amigos en el aeropuerto.",
          "Vosotros dijisteis cosas muy interesantes en la conferencia.",
          "Ellos dijeron que el restaurante era excelente.",
        ],
      },
      {
        infinitive: "dar",
        english: "to give",
        conjugations: ["di", "diste", "dio", "dimos", "disteis", "dieron"],
        examples: [
          "Yo di un regalo a mi madre por su cumpleaños.",
          "Tú diste una buena presentación en la reunión.",
          "Ella dio dinero a la organización benéfica.",
          "Nosotros dimos un paseo por el parque esta mañana.",
          "Vosotros disteis las gracias por la invitación.",
          "Ellos dieron la bienvenida a los nuevos estudiantes.",
        ],
      },
    ],
  },
  future: {
    name: "Future",
    explanation: {
      whenToUse:
        "Use the future tense to express actions that will happen. Also used for probability or conjecture in the present.",
      importantRules: [
        "Add endings to the infinitive: -é, -ás, -á, -emos, -éis, -án",
        "All verbs (AR, ER, IR) use the same endings",
        "Some verbs have irregular stems but regular endings",
        "Common irregular stems: querr-, vendr-, tendr-, pondr-, etc.",
      ],
      regularPattern:
        "hablar → hablaré, hablarás, hablará, hablaremos, hablaréis, hablarán",
    },
    verbs: [
      {
        infinitive: "hacer",
        english: "to do/make",
        conjugations: ["haré", "harás", "hará", "haremos", "haréis", "harán"],
        examples: [
          "Yo haré la comida para todos mañana.",
          "Tú harás un gran trabajo en tu nuevo empleo.",
          "Ella hará los ejercicios esta tarde después de clase.",
          "Nosotros haremos una fiesta para celebrar tu graduación.",
          "Vosotros haréis un viaje increíble por Europa.",
          "Ellos harán todo lo posible para ayudarte.",
        ],
      },
      {
        infinitive: "decir",
        english: "to say/tell",
        conjugations: ["diré", "dirás", "dirá", "diremos", "diréis", "dirán"],
        examples: [
          "Yo diré la verdad cuando me pregunten.",
          "Tú dirás unas palabras en la ceremonia de boda.",
          "Él dirá su opinión sobre el proyecto mañana.",
          "Nosotros diremos adiós a nuestros amigos en el aeropuerto.",
          "Vosotros diréis lo que pensáis en la próxima reunión.",
          "Ellos dirán los resultados del examen el viernes.",
        ],
      },
      {
        infinitive: "poder",
        english: "to be able/can",
        conjugations: [
          "podré",
          "podrás",
          "podrá",
          "podremos",
          "podréis",
          "podrán",
        ],
        examples: [
          "Yo podré terminar el trabajo antes del viernes.",
          "Tú podrás viajar cuando termines tus estudios.",
          "Ella podrá venir a la fiesta si termina temprano.",
          "Nosotros podremos comprar una casa nueva el próximo año.",
          "Vosotros podréis ver la película cuando salga en cines.",
          "Ellos podrán resolver el problema con más información.",
        ],
      },
      {
        infinitive: "poner",
        english: "to put",
        conjugations: [
          "pondré",
          "pondrás",
          "pondrá",
          "pondremos",
          "pondréis",
          "pondrán",
        ],
        examples: [
          "Yopondré más atención en mis estudios este semestre.",
          "Tú pondrás la mesa para la cena de esta noche.",
          "Él pondrá las fotos en el álbum familiar.",
          "Nosotros pondremos flores en todas las habitaciones.",
          "Vosotros pondréis música en la fiesta del sábado.",
          "Ellos pondrán los cuadros en la pared mañana.",
        ],
      },
      {
        infinitive: "tener",
        english: "to have",
        conjugations: [
          "tendré",
          "tendrás",
          "tendrá",
          "tendremos",
          "tendréis",
          "tendrán",
        ],
        examples: [
          "Yo tendré una reunión importante mañana por la mañana.",
          "Tú tendrás mucho éxito en tu nueva carrera.",
          "Ella tendrá un bebé en septiembre del próximo año.",
          "Nosotros tendremos vacaciones en agosto como siempre.",
          "Vosotros tendréis tiempo suficiente para preparar el examen.",
          "Ellos tendrán una casa grande en el campo algún día.",
        ],
      },
      {
        infinitive: "venir",
        english: "to come",
        conjugations: [
          "vendré",
          "vendrás",
          "vendrá",
          "vendremos",
          "vendréis",
          "vendrán",
        ],
        examples: [
          "Yo vendré a tu casa después del trabajo.",
          "Tú vendrás conmigo al concierto el sábado, ¿verdad?",
          "Ella vendrá a visitarnos durante las vacaciones.",
          "Nosotros vendremos temprano para ayudar con los preparativos.",
          "Vosotros vendréis en coche o en tren a la reunión.",
          "Ellos vendrán con sus familias a la celebración.",
        ],
      },
      {
        infinitive: "salir",
        english: "to leave/go out",
        conjugations: [
          "saldré",
          "saldrás",
          "saldrá",
          "saldremos",
          "saldréis",
          "saldrán",
        ],
        examples: [
          "Yo saldré de viaje la próxima semana.",
          "Tú saldrás con tus amigos este fin de semana.",
          "Él saldrá del hospital mañana por la mañana.",
          "Nosotros saldremos a cenar para celebrar tu cumpleaños.",
          "Vosotros saldréis temprano del trabajo el viernes.",
          "Ellos saldrán de la ciudad durante el puente.",
        ],
      },
      {
        infinitive: "saber",
        english: "to know",
        conjugations: [
          "sabré",
          "sabrás",
          "sabrá",
          "sabremos",
          "sabréis",
          "sabrán",
        ],
        examples: [
          "Yo sabré los resultados del examen mañana.",
          "Tú sabrás hablar español perfectamente en un año.",
          "Ella sabrá la verdad cuando le cuente todo.",
          "Nosotros sabremos qué hacer cuando llegue el momento.",
          "Vosotros sabréis cocinar paella después de la clase.",
          "Ellos sabrán la respuesta correcta después de investigar.",
        ],
      },
    ],
  },
  commands: {
    name: "Commands (Tú & Nosotros)",
    explanation: {
      whenToUse:
        "Use commands (imperative) to give direct orders, instructions, or requests. Forms vary based on formality and whether they are affirmative or negative.",
      importantRules: [
        "Affirmative tú: Usually same as él/ella present indicative form",
        "Negative tú: Use present subjunctive (no + subjunctive)",
        "Nosotros (let's): Use present subjunctive",
        "Many common verbs have irregular affirmative tú forms",
      ],
      regularPattern:
        "hablar → habla (tú affirmative), no hables (tú negative), hablemos (nosotros)",
    },
    verbs: [
      {
        infinitive: "decir",
        english: "to say/tell",
        conjugations: ["di", "(no digas)", "—", "digamos", "—", "—"],
        examples: [
          "Di la verdad sobre lo que pasó anoche.",
          "No digas mentiras a tus padres nunca.",
          "—",
          "Digamos lo que pensamos en la reunión de hoy.",
          "—",
          "—",
        ],
      },
      {
        infinitive: "hacer",
        english: "to do/make",
        conjugations: ["haz", "(no hagas)", "—", "hagamos", "—", "—"],
        examples: [
          "Haz tu tarea antes de salir a jugar.",
          "No hagas ruido porque el bebé está durmiendo.",
          "—",
          "Hagamos una fiesta para celebrar el fin de curso.",
          "—",
          "—",
        ],
      },
      {
        infinitive: "ir",
        english: "to go",
        conjugations: ["ve", "(no vayas)", "—", "vamos", "—", "—"],
        examples: [
          "Ve al supermercado y compra leche, por favor.",
          "No vayas solo al centro de noche.",
          "—",
          "Vamos al cine a ver la nueva película.",
          "—",
          "—",
        ],
      },
      {
        infinitive: "poner",
        english: "to put",
        conjugations: ["pon", "(no pongas)", "—", "pongamos", "—", "—"],
        examples: [
          "Pon la mesa para seis personas, por favor.",
          "No pongas los pies en el sofá.",
          "—",
          "Pongamos música alegre para la fiesta.",
          "—",
          "—",
        ],
      },
      {
        infinitive: "salir",
        english: "to leave/go out",
        conjugations: ["sal", "(no salgas)", "—", "salgamos", "—", "—"],
        examples: [
          "Sal de tu habitación y ven a comer.",
          "No salgas sin abrigo porque hace mucho frío.",
          "—",
          "Salgamos a caminar después de cenar.",
          "—",
          "—",
        ],
      },
      {
        infinitive: "ser",
        english: "to be",
        conjugations: ["sé", "(no seas)", "—", "seamos", "—", "—"],
        examples: [
          "Sé honesto conmigo siempre, por favor.",
          "No seas impaciente con tus hermanos pequeños.",
          "—",
          "Seamos positivos sobre el resultado del examen.",
          "—",
          "—",
        ],
      },
      {
        infinitive: "tener",
        english: "to have",
        conjugations: ["ten", "(no tengas)", "—", "tengamos", "—", "—"],
        examples: [
          "Ten cuidado al cruzar la calle.",
          "No tengas miedo de hacer preguntas en clase.",
          "—",
          "Tengamos paciencia con el proceso de aprendizaje.",
          "—",
          "—",
        ],
      },
      {
        infinitive: "venir",
        english: "to come",
        conjugations: ["ven", "(no vengas)", "—", "vengamos", "—", "—"],
        examples: [
          "Ven a mi casa esta tarde después de clase.",
          "No vengas tarde a la reunión importante.",
          "—",
          "Vengamos todos juntos para apoyar al equipo.",
          "—",
          "—",
        ],
      },
    ],
  },
};

export const pronouns = [
  "yo",
  "tú",
  "él/ella/usted",
  "nosotros",
  "vosotros",
  "ellos/ellas/ustedes",
];
export const commandPronouns = [
  "tú (affirmative)",
  "tú (negative)",
  "—",
  "nosotros",
  "—",
  "—",
];
